### ISSUE TITLE
Was the GoogleMapsCompatible forgotten by the NA?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/NamingAuthority#139]
In: http://defs.opengis.net/vocprez/object?uri=http://www.opengis.net/def/wkss/OGC/
We have this listed (4):
GlobalCRS84Pixel
GlobalCRS84Scale
GoogleCRS84Quad
WorldMercatorWGS84

But in the document we have 5 items. For some reason GoogleMapsCompatible was forgotten.

Can the NA people fix this?

**Comment by ghobona** [comment]
@joanma747 Apologies, GoogleMapsCompatible was missed because of a formatting issue on the Standard document. Specifically, Clause C.4 is not rendered as a section. We'll update the Tile Matrix Set register to add GoogleMapsCompatible.

![Screenshot 2021-10-05 at 17 15 27](https://user-images.githubusercontent.com/18121038/136062296-3e4b8bc8-912c-4446-8997-2ba698b4d75d.png)

**Comment by ghobona** [comment]
Published http://www.opengis.net/def/wkss/OGC/1.0/GoogleMapsCompatible
