### ISSUE TITLE
Linked CRS concepts showing up as "invalid"

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/NamingAuthority#165]
Following any CRSes links from https://defs.opengis.net/vocprez/object?uri=http://www.opengis.net/def/crs

e.g.

http://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/datum/OGC/0/AnsiDateDatum
http://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/crs/OGC/0/.ChronometricGeologicTime-template

**Comment by ghobona** [comment]
@rob-metalinkage This issue comes up because VocPrez encodes the VocPrez URL and not the canonical URIs in links to concepts.

So whereas users should be discovering http://www.opengis.net/def/crs, instead they are discovering https://defs.opengis.net/vocprez/object?uri=http://www.opengis.net/def/crs.
