### ISSUE TITLE
External seeAlso references are erroneously sent back to the Definitions Server

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#170]
Currently external seeAlso references are erroneously sent back to the Definitions Server. This causes an InputError (with 400 status code) because the references are URLs to external resources. 

![Screenshot 2022-03-25 at 17 49 14](https://user-images.githubusercontent.com/18121038/160175101-569d99cc-b85b-4557-9811-156e81ef71ef.png)

The Definitions Server should be modified to allow external seeAlso references to navigate to those external URLs and **not** back to the Definitions Server.

**Comment by jerstlouis** [comment]
Clicking **_see also_** on any TileMatrixSet e.g.,

http://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid

Results in a 400 Input Error.

The URL that _see also_ links to is e.g.,

https://defs.opengis.net/vocprez/object?uri=http%3A//schemas.opengis.net/tms/1.0/json/examples/GNOSISGlobalGrid.json

The value of the uri query parameter, the external link, is an invalid URI for the definition server.

This makes it impossible for users/developers to manually retrieve a TileMatrixSet definition from the registry.

To correct this error, for external links, the link should directly point to the external _See Also_ link, instead of linking to vocprez/object with a `?uri=` pointing to an external link that is an invalid URI.

**Comment by cportele** [comment]
Copied from #197: 

I also get 400 errors for most definitions server requests. In my case the behavior depends on the browser:

Chrome (latest version): When I click on http://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid, I get a 307 redirect due to HSTS to https://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid which in turn results in a 303 redirect to http://defs.opengis.net/vocprez/object?uri=https://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid which returns 400 Bad Request.

This is what I see in the browser:

<img width="1567" alt="Bildschirmfoto 2022-09-19 um 18 40 15" src="https://user-images.githubusercontent.com/4245251/191069045-d720d48f-7379-4329-8944-07b367773581.png">

Firefox: There is no 307 HSTS redirect and I directly get a 303 redirect to http://defs.opengis.net/vocprez/object?uri=http://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid (note: http, not https).

When I try https://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid in Firefox, I also get the 400 error.

**Comment by jerstlouis** [comment]
I believe the issue reported by @cportele needs to be addressed as well but it is a different issue, not related to the external see also link, but specifically related to https:

- The following (the first redirects the second) also return a 400 for me:
   - https://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid
   - http://defs.opengis.net/vocprez/object?uri=https://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid

Because the URIs are defined as http, not https, the `uri=` query parameter, currently automatically set up with redirection, should never an https value, even when the definition server is being accessed via https. Avoiding unnecessary re-direction (#109) would also side-step this issue.

**Comment by rob-metalinkage** [comment]
We have a fix for the seeAlso being pushed through - it will use a local link only if we have information about the link, otherwise support the link - however we need to work on the issue of being allowed to jump to a http link from a https resource...

http://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid links to the resource with that identifer

so does

https://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid 

except in this case there is no such resource - the URIs are not the same in the baseline architecture of the web...

so the question is what is the requirement for customised handling of "near misses" - or a policy that declares they should be the same (which we need to formally propose and adopt)...

should we find the "close match" and give the user a big alert that they reached this resource via a non-canonical URI ?

the same issue is handling sameAs where an explicit declaration, and also the issue of version negotiation #116 

please post this as a NA discussion needing policy determination - we will update infrastructure to meet requirements agreed.

**Comment by rob-metalinkage** [comment]
Note #116 has been resolved for the name type specification - not the general case.

**Comment by rob-metalinkage** [comment]
Assigning to Alejandro Villar to explore UI options and to configure entailment as per this requirement where a sameAs is declared.

**Comment by cportele** [comment]
> http://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid links to the resource with that identifer
>
> so does
>
> https://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid
>
> except in this case there is no such resource - the URIs are not the same in the baseline architecture of the web...

If there is no resource https://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid, then the HSTS redirects must be deactivated on the server, because HSTS redirects the first URI to the second resource.

**Comment by rob-metalinkage** [comment]
Can you please identify your http client that is triggering this redirect - this does not happen on Google Chrome or Microsoft Edge for me.  It may not be the server but some intermediate proxy?

I have checked apache configuration on the definition server and hsts is not enabled - will check if it is at the top level of the domain.

**Comment by cportele** [comment]
I am using Google Chrome, Version 105.0.5195.125 (arm64). There is no proxy. 

I checked the HSTS information for www.opengis.net in Chrome and based on it looks as if www.opengis.net sent HSTS headers at least on September 14 with an expiry in six months (March 2023):

* dynamic_sts_domain: www.opengis.net
* dynamic_upgrade_mode: FORCE_HTTPS
* dynamic_sts_include_subdomains: true
* dynamic_sts_observed: 1663158971.616693
* dynamic_sts_expiry: 1678883771.616687

I removed the HSTS cache for www.opengis.net and now the error is gone. So, for me the problem is solved, but there may be some issue in the infrastructure.

**Comment by rob-metalinkage** [comment]
thanks - if we get other reports we might need to look at catching these somehow and warning users. Assigning to Kevin for advice.

**Comment by avillar** [comment]
Bugfix for seeAlso handling is live in production (see https://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/tilematrixset/OGC/1.0/WorldMercatorWGS84Quad)

**Comment by jerstlouis** [comment]
Thank you @avillar @rob-metalinkage . It is great that this is now fixed!

Please note that different related problems remain:
- https://www.opengis.net/def/tilematrixset/OGC/1.0/WorldMercatorWGS84Quad -- This also results in a 400. When/While a re-direct is needed, I would suggest to re-direct to http://defs.opengis.net/vocprez/object?uri=http://www.opengis.net/def/tilematrixset/OGC/1.0/WorldMercatorWGS84Quad instead of http://defs.opengis.net/vocprez/object?uri=https://www.opengis.net/def/tilematrixset/OGC/1.0/WorldMercatorWGS84Quad which does not have the issue. Should we file a separate issue for this, so that this one can be closed?
- That particular _see also_ ( http://schemas.opengis.net/tms/1.0/json/examples/GNOSISGlobalGrid.json ) is not the resource that we would like the link users to, and **_neither_** is the [newer version of that example](http://schemas.opengis.net/tms/2.0/json/examples/GNOSISGlobalGrid.json). The JSON representation should be sourced from the [TileMatrixSet registry GitHub repo](https://github.com/opengeospatial/2D-Tile-Matrix-Set/tree/master/registry), which does not have all of the exact same files, in this case the source [would be here](https://raw.githubusercontent.com/opengeospatial/2D-Tile-Matrix-Set/master/registry/json/GNOSISGlobalGrid.json). #199 is about deprecating those old examples (where I clarify that actually we should not link to neither the 1.0 or 2.0 examples from the schemas directory), and #203 is about the ingest process from the GitHub repo, but the comments there are focused on SKOS view rather than returning the JSON/XML encodings themselves. #109 was about returning the definition directly, but is now closed. Is this remaining problem sufficiently covered by existing open issues?

Thank you.

**Comment by ghobona** [comment]
Thanks @avillar !
