### ISSUE TITLE
prov:wasDerivedFrom is not appearing on VocPrez

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#181]
The new revision of the Definitions Policy uses `prov:wasDerivedFrom` in the [CURIE register](http://www.opengis.net/def/curie) for specifying the URI to which the registered CURIE applies.

Unfortunately, VocPrez does not appear to be showing triples that contain `prov:wasDerivedFrom` as a predicate.

Please update the VocPrez configuration to support the predicate.

**Comment by ghobona** [comment]
The source files are at https://github.com/opengeospatial/NamingAuthority/tree/master/incubation/CURIEs

**Comment by avillar** [comment]
@rob-metalinkage, apparently `dct:provenance`, `dct:source` and `prov:wasDerivedFrom` go through some sort of special process when VocPrez is generating the view for the Concept, but then they are just... ignored. I have removed this and deployed the result on defs-dev ([example 1](http://defs-dev.opengis.net/vocprez/object?uri=http://www.opengis.net/def/curie/ogc/1.0/crs/EPSG), [example 2](http://defs-dev.opengis.net/vocprez/object?uri=http://www.opengis.net/def/curie/ogc/1.0/rel/conformance)); @ghobona, please check that it is all right there so that we can promote it to defs.

**Comment by ghobona** [comment]
Yes, it's perfect. Thank you.

**Comment by avillar** [comment]
The fix is live.

**Comment by ghobona** [comment]
Excellent!
