### ISSUE TITLE
400 Input Error on TileMatrixSet "see also"

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/NamingAuthority#197]
Clicking _see also_ on any TileMatrixSet e.g.,

http://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid

Results in a **_400 Input Error_**.

The URL that see also links to is e.g.,

https://defs.opengis.net/vocprez/object?uri=http%3A//schemas.opengis.net/tms/1.0/json/examples/GNOSISGlobalGrid.json

This makes it impossible for users/developers to manually retrieve a TileMatrixSet definition from the registry.

However, please note that:
- The examples from schemas.opengis.net/tms/1.0 are deprecated. The data model has changed for [2DTMS&TSMD version 2.0](https://docs.opengeospatial.org/is/17-083r4/17-083r4.html). The new schemas will be deployed to `/tms/2.0`, however that should not be relevant because:
- The examples in the schemas/ folder and 2DTMS&TSMD standard are not the authoritative source for the TileMatrixSet definitions. Rather, the TileMatrixSet registry itself, as presented by the definition server, is.
- Because of this, it would seem more correct to call these links (accessed from the canonical URI of an entry in the TileMatrixSet register) "JSON representation" and "XML representation", or "definition", or "see also JSON/XML definition/representation" instead of  "see also" implying that this is a different web resource.
- The TileMatrixSet registry can source its content from the [registry directory](https://github.com/opengeospatial/2D-Tile-Matrix-Set/tree/master/registry) of the GitHub TileMatrixSet repository (containing both the JSON and XML definitions). The definition server could make its own copy in a database or local directory for security or other reasons by cloning the copy, and sync by doing a pull/copy.

Related to #170 .

**Comment by ghobona** [comment]
When I click on http://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid , I get a valid response. See the attached screenshot. The link worked on both Safari and Chrome.

<img width="1406" alt="Screenshot 2022-09-19 at 18 27 29" src="https://user-images.githubusercontent.com/18121038/191066734-d735fd8c-ed5a-4e8a-9412-dd96f84e822e.png">

**Comment by ghobona** [comment]
The second part of the Issue description above is a duplicate of https://github.com/opengeospatial/NamingAuthority/issues/170 and https://github.com/opengeospatial/NamingAuthority/issues/198

@jerstlouis Please move the bullet points to https://github.com/opengeospatial/NamingAuthority/issues/198 and close this GitHub Issue (#197) so that we can keep all relevant comments in the same issue.

**Comment by cportele** [comment]
@ghobona - I have the same issue as Jerome. In my case the behavior depends on the browser:

Chrome (latest version): When I click on http://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid, I get a 307 redirect due to HSTS to https://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid which in turn results in a 303 redirect to http://defs.opengis.net/vocprez/object?uri=https://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid which returns 400 Bad Request.

This is what I see in the browser:

<img width="1567" alt="Bildschirmfoto 2022-09-19 um 18 40 15" src="https://user-images.githubusercontent.com/4245251/191069045-d720d48f-7379-4329-8944-07b367773581.png">

Firefox: There is no 307 HSTS redirect and I directly get a 303 redirect to http://defs.opengis.net/vocprez/object?uri=http://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid (note: http, not https).

When I try https://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid in Firefox, I also get the 400 error.

**Comment by jerstlouis** [comment]
Thank you @ghobona .

> When I click on http://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid , I get a valid response. See the attached screenshot. The link worked on both Safari and Chrome.

I meant clicking on the **_See Also_**, not the URI (that just sends back to the current page).

> The second part of the Issue description above is a duplicate of https://github.com/opengeospatial/NamingAuthority/issues/170 and https://github.com/opengeospatial/NamingAuthority/issues/198

Yes I discovered #170 afterwards and was not sure whether it was a duplicate of this issue or not.
It was not obvious from the title: _External seeAlso references are erroneously sent back to the Definitions Server_, but that is indeed what causes this issue.

I have moved the bullet points to #198, and added the other details to #170. Closing this issue.
