### ISSUE TITLE
Deprecate v1.0 tile matrix set examples

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#199]
The examples from schemas.opengis.net/tms/1.0 are deprecated. The data model has changed for [2DTMS&TSMD version 2.0](https://docs.opengeospatial.org/is/17-083r4/17-083r4.html). The new schemas will be deployed to /tms/2.0.

Reported by @jerstlouis

**Comment by jerstlouis** [comment]
Thank you @ghobona .

And as I clarified in #198:

- **The definition server should _not_ link to or copy from the TileMatrixSet definitions in neither `/tms/1.0` nor `/tms/2.0`**.
- The examples in the schemas/ folder and 2DTMS&TSMD standard are **not** the authoritative source for the TileMatrixSet definitions. Rather, the TileMatrixSet registry itself, as presented by the definition server, is.
- The TileMatrixSet registry can source its content from the [registry directory](https://github.com/opengeospatial/2D-Tile-Matrix-Set/tree/master/registry) of the GitHub TileMatrixSet repository (containing both the JSON and XML definitions). The definition server could make its own copy in a database or local directory for security or other reasons by cloning the copy, and sync by doing a pull/copy.

**Comment by jerstlouis** [comment]
Thank you very much @avillar, @rob-metalinkage, everyone, for updating the TileMatrixSet definitions to point to the Tile Matrix Set registry definitions using 2DTMS version 2.0.

Until #192 (multiple _see also_) is resolved, would it be possible to please link to (_see also_) the **JSON** definitions ( https://github.com/opengeospatial/2D-Tile-Matrix-Set/tree/master/registry/json ) rather than the XML ones?

The _OGC API - Tiles_ [TileSet conformance class](https://opengeospatial.github.io/ogcna-auto-review/20-057.html#toc30) (akin to a more useful "_Core_" than the minimalistic _Core_) explicitly requires support ([requirement 8A](https://opengeospatial.github.io/ogcna-auto-review/20-057.html#toc32)) for the JSON definition, whereas the XML ones are for a [separate conformance class](https://opengeospatial.github.io/ogcna-auto-review/20-057.html#toc62). We expect much fewer implementations to implement and support the XML definition, which is only provided mostly for continuity with the WMTS legacy. Similar to how many more _OGC API - Features_ implementations suport GeoJSON than GML.

This simple fix would greatly improve the immediate useability of the TileMatrixSet register for the use case of manually exploring it in a browser.

Thank you!

**Comment by rob-metalinkage** [comment]
@jerstlouis - yes happy to add these links - but if we link to github this way then the resource will not be given the correct MIME type - we are currently look at how best to link to multiple arbitrary locations and preserve correct mime-types - it may be a matter of a pipeline accessing them from the registered source and loading them into a proxy location we can expose with correct MIME types - or else ask providers to ensure they have a canonical location that uses correct MIME types.

We could use these links and expect systems navigating the machine readable content to make allowances but this is adding a layer of complexity in the wrong place - expecting consumers to predict and cope with non standard behaviours.

**Comment by jerstlouis** [comment]
@rob-metalinkage Thanks, my suggestion here was simply to use the JSON ones instead of the XML ones that are already there currently (linking to the GitHub).

I am not sure I understand the MIME type issue. Do you mean the `Content-Type:` that is returned by GitHub in HTTP response headers does not have the proper media type `application/json`?
I do see that GitHub returns `< content-type: text/plain; charset=utf-8`.

> it may be a matter of a pipeline accessing them from the registered source and loading them into a proxy location we can expose with correct MIME types 

Yes, this is what we would hope for, that some sort of database or local file storage managed by OGC could serve that purpose, and pull from the GitHub registry when an update is needed (whether that is an automated or a manual process via issues here). Ideally, this would also support content negotiation (#124) and returning the actual definition (#109) at the definition server canonical URI itself (#198).

Thanks!

**Comment by ghobona** [comment]
@jerstlouis @rob-metalinkage Please note that the data that was ingested into the Definition Server already has links to both the JSON and XML representations. However, VocPrez does not appear to have been configured to display multiple seeAlso statements, so only one statement is currently being shown. It's the same issue as [#192](https://github.com/opengeospatial/NamingAuthority/issues/192).

**Comment by ghobona** [comment]
The source file is at https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/20220926_tile_matrix_set_register/tms.ttl

**Comment by jerstlouis** [comment]
@ghobona @rob-metalinkage @avillar Yes that is correct. My suggestion was a work-around for #192 considering the much greater importance of the JSON encoding for TileMatrixSets for _OGC API - Tiles_ compared to XML. So does it just happen to keep the _last_ see also entry? If so I could go through and submit a pull request that moves the .json to appear after the .xml in the .ttl file.

This temporary work around would greatly improve the immediate usability of the TileMatrixSet registry.

Thanks.

**Comment by ghobona** [comment]
Links to the v1.0 tile matrix set examples have now been removed.
