### ISSUE TITLE
IAU Planetary CRS Definitions

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#212]
The Planetary DWG has been preparing a tree within the OGC Definitions Server for publishing planetary CRS definitions specified by the IAU.

Once configured, http://www.opengis.net/def/crs/IAU/2015 would forward requests to http://voparis-vespa-crs.obspm.fr:8080/ws/IAU/2015

Before OGC Staff configure opengis.net URIs for the IAU definitions, please review the content and let us know by December 20th if there are any concerns.

**Comment by cmheazel** [comment]
Web access to the CRS Registry is through http://voparis-vespa-crs.obspm.fr:8080/web/

It's surprising how much content is on this site. It includes multiple CRS for all of the planets as well as the Sun, Moon and a number of asteroids.  It would be best if we could link to all of this content, not just the planetary CRS.

**Comment by chris-little** [comment]
@ghobona All the WKT that I saw used the keyword `PROJCRS`. Will this be a problem? What happens when the PROJCRS work in the OGC CRS SWG delivers?

**Comment by cmheazel** [comment]
@chris-little The [Testbed-18: Reference Frame Transformation Engineering Report](http://ogc.pages.ogc.org/T18-3Dplus_Data_Standards_and_Streaming/documents/D025/document.html) includes a discussion on the deficiencies of WKT for non-terrestrial CRS and how to address them.  Are these recommendations in-line with the PROJCRS work?

**Comment by chris-little** [comment]
@cmheazel I am not sure. @rogerlott or other active CRS SWG memeber would be the people to ask. I am not sure that the PROJCRS work has made much progress.

**Comment by ghobona** [comment]
@chris-little `PROJCRS` is from Clause 9 of the the [WKT CRS](http://docs.opengeospatial.org/is/18-010r7/18-010r7.html) spec. It means projected CRS.

**Comment by RogerLott** [comment]
@chris-little, Are we conflating our proj's?

 'Lack of progress' is I think referring to the proposal from Proj to endorse ProjJSON as an OGC community standard as alternative to to CRS WKT. When the proposal was discussed at the CRS DWG the concept of CRS JSON was agreed as being needed and endorsed, but on the grounds that take-up outside of the Proj Community was expected to be greater if the specification were an OGC Implementation Standard rather than an OGC Community Standard, the proposers were invited to submit a proposal for an OGC Implementation Standard matching WKT2 18-010r[latest].   

This is not to be confused with PROJCRS which is used the keyword specified in 18-010 (WKT2) to indicate that the definition is for a CRS where CRS_type = projected. Anything with a map projection as a component in its definition. If the map projection is for mapping a celestial body, that is fine, the use of PROJCRS is correct.

[An aside, which perhaps should be a separate comment/issue, so @ghobona feel free to move out to elsewhere. There is a potential technical issue with map projections for planetary bodies - the mathematics underpinning many map projections for the earth use approximations which are constructed around the flattening (ratio of semi-major and semi-minor axes) of the earth's ellipsoidal model, which by planetary standards is very small [relatively speaking, earth is nearly a sphere]. For ellipsoids with significantly different flattening these used for earth ellipsoids assumptions may [and in some cases will] not be valid, and projection formulae different to those for the earth will be needed. Yet the IAU definitions do not (or at least did not) take this into consideration. Some of the IAU models (and all those of the small sample I looked at for the sun) use a sphere rather than ellipsoid, so this potential concern is not an issue. However many astroids and planets have very different flattening to the earth. The generallity of the concern was sufficient for the CRS DWG to say some years ago that on technical grounds we are not sure that all entries in the IAU catalogue should be endorsed in an OGS CRS registry, even if those approximations were in widespread use in the planetary science community. Following the formation of the Planetary DWG, considerations of that issue have been passed from the CRS DWG to the Planetary DWG].

**Comment by chris-little** [comment]
@RogerLott Yes I was. Thank you for the helpful clarification and raising the siginficant issue.

@ghobona I suggest that a conservative safe approach would be to adopt/point to all the IAU registered CRSs, as they are now. Then as planetary expertise and measurement improve and new, more accurate CRS are created, possibly even involving triaxial ellipsoids, and registered, then the older less accurate CRSs could be deprecated.

**Comment by jlaura** [comment]
I am a planetary scientists who work with these projects day in and day out with the USGS Astrogeology group. Hopefully weighing in here is appropriate! If not, please feel free to hide or remove these comments.

1. The linked definitions and the ones linked as [raw wkt here](https://raw.githubusercontent.com/pdssp/planet_crs_registry/main/data/result.wkts) (which I believe are just a mirror) are the ones that are (should be) being used day in and day out.
2. Some of those projections will not work with the vast majority of tools because they specify a triaxial ellipsoid (which is significantly more accurate, but requires specialized tooling for the map projection algorithms).
3. Disregarding small bodies for a moment, the vast majority of hard bodies are best represented by a sphere including a recent push to define Mars using a sphere.
4. Having these codes forward through opengis.net, if approved, will be absolutely terrific as it lets us start to propagate them out into the broader ecosystem. That is all to say that I really appreciate this groups work looking at the IAU codes and getting them propagated out.

**Comment by AndrewAnnex** [comment]
@ghobona I am also a planetary scientist and I am interested in moving this forward. Is it possible/acceptable for external contributes to make the changes necessary?

**Comment by ghobona** [comment]
@AndrewAnnex  Yes, indeed. OGC welcomes proposals from the general public. At a high level, we follow the process described in the [OGC Naming Authority policies and procedures](https://docs.opengeospatial.org/pol/09-046r6.html#_processing_of_name_assignment_requests).

Upon receiving a proposal for registration of a planetary CRS definition, the OGC Naming Authority will consult with the [OGC's Planetary DWG](https://www.ogc.org/projects/groups/planetarydwg).

To kick off the process, please create a new [GitHub Issue](https://github.com/opengeospatial/NamingAuthority/issues) and attach (or reference) the planetary CRS definition that you would like to have registered.

**Comment by AndrewAnnex** [comment]
@ghobona although I am eager to to contribute this but I don't understand concretely what I'd need to do within the PR. Can I just contribute a CSV table with the URIs (although the original french server appears to be down)? Where should I put my changes within the repo, a new folder under incubation?  

Having an example PR to follow would be helpful also but it there doesn't seem to be a good example PR to follow.

**Comment by AndrewAnnex** [comment]
@ghobona re-reading your comment, while I could open a new issue it would be redundant with this issue. I want all CRSs defined at https://raw.githubusercontent.com/pdssp/planet_crs_registry/main/data/result.wkts to be included. Hopefully the server http://voparis-vespa-crs.obspm.fr:8080/ws/IAU/2015 will be fixed soon but I'd hope that the OGC could just serve these directly rather than relying on a server that doesn't appear to be maintained well.

**Comment by AndrewAnnex** [comment]
I think we can close this issue for now @ghobona, thanks for the assist!
