### ISSUE TITLE
OGC bodies sync with the portal

### ISSUE THREAD

**Issue by pzaborowski** [opengeospatial/NamingAuthority#213]
I'd like to collect all the Working Groups from the portal to generate entities/bodies.
The plan is to generate URIs based on the title (lowercase, without white and special signs).

**Comment by pzaborowski** [comment]
@rob-metalinkage I'll do it myself, but please help me to identify where is the portal connection configuration we can use.

**Comment by avillar** [comment]
I've done some refactoring of the workflows so that:

1. [The JSON-LD uplift + entailment and validation workflow](https://github.com/opengeospatial/NamingAuthority/blob/master/.github/workflows/entail_and_validate_changes.yml) is reusable and/or can be called manually by specifying the added, modified and removed files.
2. There is a new "on push" workflow ([entail_validate_on_push.yml](https://github.com/opengeospatial/NamingAuthority/blob/master/.github/workflows/entail_validate_on_push.yml)) that does the first part of the old workflow (detect changes)
3. There's a [download_json.yml](https://github.com/opengeospatial/NamingAuthority/blob/master/.github/workflows/download_json.yml) workflow run by cron every day at 3.00, that downloads the files configured in json_downloads.json (root of the repo) and triggers the JSON-LD uplift + entailment/validation workflow if changes are found. **This is how `[incubation/working-groups/working-groups.*](https://github.com/opengeospatial/NamingAuthority/tree/master/incubation/working-groups)` are generated right now**. 

Instead of using the title or abbv for the working groups, I've opted for the numeric id in the [JSON source file](https://portal.ogc.org/public_ogc/api/working_groups.php), since Greg confirmed that it's stable (while the other values could be subject to changes, e.g., when fixing typos). 

The [JSON-LD uplift process](https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/working-groups/working-groups.yml) for the working groups also detects SWG's and DWG's (by looking for those words on the name of the group). It also adds the standard stuff (type skos:Concept, skos:inScheme). Of course, this can be improved.

I'm now working on another workflow to periodically download and parse the Document to SWG Google Spreadsheet and generate an `incubation/working-groups/docs.ttl` with the matches in the form `<Doc URI> prov:wasAttributedTo <Body URI>`.

**Comment by rob-metalinkage** [comment]
This is now operational - and a simplified spreadsheet to support the mapping  of SWGs to docs is now available at: 
https://docs.google.com/spreadsheets/d/1pqFUR6F7FM5ASgKRKev8mLvR5NoXilq5BX0rZQG6fQM/edit#gid=0

Currently a manual git action is used to sync this to the staging server, we will review these  updates before committing to production.
