### ISSUE TITLE
Interoperability between vocabulary registers of OGC, ISO and others.

### ISSUE THREAD

**Issue by estubkjaer** [opengeospatial/NamingAuthority#24]
There are a number of vocabulary services and registers available across the industry. Examples include:
- OGC Definitions Server at http://www.opengis.net/def/
- OGC Glossary of Terms (RDF version) at http://www.opengis.net/def/glossary/
- ISO/TC 211 Terminology Maintenance Group (TMG) offers a Glossary of Terms at https://github.com/ISO-TC211/TMG, and an online version of this Multi-Lingual Glossary of Terms (MLGT) is available at Geolexica https://www.geolexica.org/
- BARTOC, the Basel Register of Thesauri, Ontologies & Classifications, is a database of about 90 Knowledge Organization Systems / terminology registries available at https://bartoc-skosmos.unibas.ch/en/
- CaLAThe, the Cadastre and Land Administration Thesaurus, was included in BARTOC https://bartoc-skosmos.unibas.ch/CaLAThe/en/ and in Dec. 2019 also at https://www.opengis.net/def/CaLAThe/4.0/
- OSGeo is establishing a lexicon committee at https://wiki.osgeo.org/wiki/Lexicon_Committee

These services are based on SKOS and related formalisms, but there's a need for improved practices to harvest the potential of semantic interoperability between the different services, including enabling federated or distributed search between the different services/registers.

CaLAThe was included into BARTOC by responding to an invitation with a copy of CaLAThe in terms of a skos/rdf file.

‘.. main goal [of BARTOC] is to list as many Knowledge Organization Systems as possible at one place in order to achieve greater visibility, highlight their features, make them searchable and comparable, and foster knowledge sharing. BARTOC includes any kind of KOS from any subject area, in any language, any publication format, and any form of accessibility. BARTOC’s search interface is available in 20 European languages and provides two search options: Basic Search by keywords, and Advanced Search by taxonomy terms. ’ http://bartoc.org/en/content/about

How might the geospatial community respond to this and improve domain-internal practices as well?

**Comment by rob-metalinkage** [comment]
Have registered for this workshop  https://sharedconcepts.github.io/agenda.html where I can present on best practices, roadmap and challenges

**Comment by rob-metalinkage** [comment]
Discussions with ISO ongoing... yet to identify an effective forum to pursue this goal however.

**Comment by ghobona** [comment]
I suggest that the next Open Standards and Open Source Software Code Sprint (likely in Q1 or Q2 2024) includes a breakout session on identifying semantic relationships between concepts in the OGC, OSGeo, BARTOC, CaLAThe and ISO vocabularies. I imagine an output of the breakout session being crosswalk with columns for sameAs, related, narrower, broader, exactMatch, etc. from each vocabulary.

**Comment by ghobona** [comment]
Cc: @nilshempelmann Please see the comment above about coordination through the Location Innovation Academy.

**Comment by ErikStubkjaer41** [comment]
Working through the Glossary of the Location Innovation Academy made me aware of geospatial learning resources, besides the ISO/TC 211 Multi-Lingual Glossary of Terms (MLGT) https://isotc211.geolexica.org/
which I knew already, namely

- OGC e-learning http://opengeospatial.github.io/e-learning/index.html
- OGC APIs https://ogcapi.ogc.org/
- GeoServer https://geoserver.org/
- EUs INSPIRE glossary https://inspire.ec.europa.eu/glossary/

I'll concact @nilshempelmann on the Glossary

**Comment by ErikStubkjaer41** [comment]
Concerning LIA Glossary https://academy.ogc.org/mod/glossary/:

In [CaLAThe](http://cadastralvocabulary.org) we supplemented the dry definitions, etc. with graphic, cf. [CaLAThe presentations](http://cadastralvocabulary.org/GeneralOverview/GraphicalOverview.php). To support the [Location Innovation Academy](https://academy.ogc.org/?) learning process, I drafted a hierarchy of geospatial terms [here.](https://cadastraltrees.aau.dk/SemanticWeb/LIAglossaryHierarchy.html) The context is my own learning notes at https://cadastraltrees.aau.dk/SemanticWeb/SemanticWebLinkedDataVocabularies.html.
I would be happy to further contribute to a joint advancement of geospatial vocabularies. (cf. mail 17-08-2023 18:34)

**Comment by ghobona** [comment]
Thank you @ErikStubkjaer41 ! It's nice visualisation of the terms.

@nilshempelmann Please have a look at the visualisation.

**Comment by pebau** [comment]
> Working through the Glossary of the Location Innovation Academy made me aware of geospatial learning resources, besides the ISO/TC 211 Multi-Lingual Glossary of Terms (MLGT) https://isotc211.geolexica.org/ which I knew already, namely
> 
>     * OGC e-learning http://opengeospatial.github.io/e-learning/index.html
> 
>     * OGC APIs https://ogcapi.ogc.org/
> 
>     * GeoServer https://geoserver.org/
> 
>     * EUs INSPIRE glossary https://inspire.ec.europa.eu/glossary/
> 
> 
> I'll concact @nilshempelmann on the Glossary

adding coverage/datacube-related resources:

- https://earthserver.world/wcs
- OGC public Coverages.DWG wiki: http://myogc.org/go/coveragesDWG
- coverage/datacube sandbox: https://standards.rasdaman.com

**Comment by ghobona** [comment]
https://github.com/metanorma/metanorma-ogc/issues/34#issuecomment-2145046042

The plugin for importing glossarist datasets is at https://github.com/metanorma/metanorma-plugin-glossarist

The ISO/TC 211 glossarist database can be found at https://github.com/geolexica/isotc211-glossary

A number of proposals are being considered:

1. One of the proposals is to export OGC’s Glossary of Terms from OGC RAINBOW as well as any other registers from RAINBOW to the yaml format supported by Glossarist. This solution requires the least amount of development effort.
2. Another proposal is to implement a plugin that directly pulls in the terms of a skos:Collection or skos:ConceptScheme published by OGC RAINBOW. This is the most ideal solution because it involves the least number of transformation steps.

**Comment by rob-metalinkage** [comment]
Option 2 is far preferable - we should be promoting standardised data exchange methods rather than custom adaptors.

If there are extensions to SKOS model needed to support something specific we can define a profile. 

In general we may have multiple types of controlled vocabularies and references - e.g. dependencies and references - so in general a extensible profile mechanism is going to be far more useful for different referencing cases.

**Comment by ghobona** [comment]
Closed this Issue because we now have a way to import TC 211 terms.
 
An index file can be found at https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/geolexica-tc211/data/tc211/0.csv
 
The asciidoc files to import the definitions from can be found at https://github.com/opengeospatial/NamingAuthority/tree/master/incubation/geolexica-tc211/data/tc211
 
Once you have copied the tc211 subfolder into your metanorma project, you can then simply include the definitions as you do with any other asciidoc files.
 
For example, by using this snippet.
 
`include::./glossaries/tc211/703_coordinate_reference_system.adoc[]`

**Comment by ReesePlews** [comment]
hello @ghobona thank you for using ISO/TC 211 Multi-lingual glossary of terms ([Geolexica](https://isotc211.geolexica.org/)).

i can see how this method will work easily with metanorma authoring. 

i am not trying to mess up what you have suggested for your members, however i am concerned that when i make updates to Geolexica, the data your members have copied will be the old version. presently Geolexica is not updated so frequently, however as more people are using it, i want to make those update times more frequent. this has been discussed with the Geolexica developers. 

if i am understanding your earlier post correctly, each ogc project developed in metanorma will now have a tc211 subfolder with asciidoc files (one per each tc211 terminological entry) that can be included directly into the specific ogc project document, using the asciidoc include command.

i wonder if there would be a better way that did not require making these copies. possibly using geolexica to "discover" the required term/def and then some way/some method more easily accessing that authoritative data and "placing it" into the ogc project metanorma document. right now i am not sure what that way/method would be, but i just think it could be better than a copy.... unless i am not clearly understanding what the tool you have made does.

in geolexica right now we have a "copy" button that copies the text version of the entry to the copy/paste buffer. perhaps something similar could be made, like a copy of the authoritative geolexica asciidoc file. 

i will discuss with @ronaldtse and his geolexica developers, unless you have already asked them about this. perhaps metanorma already has such a custom function to pull those asciidoc files via a url... i am sure Ron and his team will have some good advice on this. 

again, thank you for promoting geolexica to the ogc members.
